CREATE TABLE user_token (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRES_IN INT DEFAULT 72,
    TOKEN CHAR(36),
    USED BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE user_ws (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LOGIN VARCHAR(60) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL
);